apiVersion: v1
description: nucliadb Chart
name: nucliadb
version: 0.0.1
appVersion: 0.0.1
keywords:
  - nucliadb
  - nuclia
home: https://nuclia.com
icon: https://nuclia.com/logo.png
sources:
  - https://github.com/nuclia/nucliadb
maintainers:
  - name: Nuclia
    email: nucliadb@nuclia.com
dependencies:
  - name: nucliadb-ingest
  - name: nucliadb-node
  - name: nucliadb-writer
  - name: nucliadb-reader
