name: nucliadb (py)
env:
  API_VERSION: 1
  COMPONENT: nucliadb
on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/nucliadb.yml"
      - "charts/nucliadb/**"
      - "Dockerfile"
      - "nucliadb/**"
      - "nucliadb_utils/**"
      - "nucliadb_ingest/**"
      - "nucliadb_writer/**"
      - "nucliadb_fields_tantivy/**"
      - "nucliadb_paragraphs_tantivy/**"
      - "nucliadb_relations/**"
      - "nucliadb_node/**"
      - "nucliadb_vectors2/**"
      - "nucliadb_one/**"
      - "nucliadb_reader/**"
      - "nucliadb_search/**"
      - "nucliadb_models/**"
      - "nucliadb_protos/**"
      - "nucliadb_cluster/**"
      - "nucliadb_models/**"
      - "nucliadb_train/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nucliadb.yml"
      - "charts/nucliadb/**"
      - "Dockerfile"
      - "nucliadb/**"
      - "nucliadb_utils/**"
      - "nucliadb_ingest/**"
      - "nucliadb_writer/**"
      - "nucliadb_fields_tantivy/**"
      - "nucliadb_paragraphs_tantivy/**"
      - "nucliadb_relations/**"
      - "nucliadb_node/**"
      - "nucliadb_vectors2/**"
      - "nucliadb_one/**"
      - "nucliadb_reader/**"
      - "nucliadb_search/**"
      - "nucliadb_models/**"
      - "nucliadb_protos/**"
      - "nucliadb_cluster/**"
      - "nucliadb_models/**"
      - "nucliadb_train/**"

jobs:
  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install package
        run: |
          pip install -r code-requirements.txt
      - name: Run pre-checks
        run: |
          flake8 nucliadb_one --config=nucliadb/setup.cfg
          isort -c --profile black nucliadb/
          black --check --verbose nucliadb

  # Job to run tests
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      # setup docker, as we need to pull the node image to run the tests
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          profile: default
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install the package
        run: |
          pip install -r test-requirements.txt
          pip install -r nucliadb_one/requirements-sources.txt
          pip install -r nucliadb_ingest/requirements.txt
          pip install -e nucliadb_ingest
          pip install -r nucliadb_search/requirements.txt
          pip install -e nucliadb_search
          pip install -r nucliadb_writer/requirements.txt
          pip install -e nucliadb_writer
          pip install -r nucliadb_reader/requirements.txt
          pip install -e nucliadb_reader
          pip install -e nucliadb_one
          pip install -r nucliadb/requirements.txt
          pip install -e nucliadb

      - name: Install rust binding for testing
        run: |
          maturin build -m nucliadb_node/binding/Cargo.toml
          pip install target/wheels/*cp39-cp39-manylinux_2_31_x86_64.whl

      - name: Check mypy
        run: |
          MYPYPATH=./mypy_stubs mypy nucliadb/

      - name: Run tests
        run: |
          pytest -rfE --cov=nucliadb_one -s --tb=native -v --cov-report xml --cov-append nucliadb/nucliadb

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: nucliadb

  push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nuclia/nucliadb:latest

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags')
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-2016"]
    env:
      CIBW_ARCHS_LINUX: auto aarch64
      CIBW_ARCHS_MACOS: x86_64 universal2 arm64
      # Building for one python version is enough, since this is a
      # ctypes-based 'universal binary wheel' (py3-none-*) not
      # linked to a specific python version or implementation.
      CIBW_BUILD: "cp39-*"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up msbuild (Windows-only)
        uses: microsoft/setup-msbuild@v1.0.2
        if: startsWith(matrix.os, 'windows')

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Build wheels
        run: pipx run cibuildwheel --output-dir dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
