name: Release NucliaDB Utils

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nucliadb_utils_release.yml"
      - "nucliadb_utils/VERSION"

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install -r nucliadb_utils/requirements.txt
          pip install wheel

      - name: Install nucliadb_utils
        run: pip install -e ./nucliadb_utils

      - name: Build wheels
        run: pip wheel --no-deps -w dist ./nucliadb_utils

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
