name: Release NucliaDB Client

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/nucliadb_client_release.yml"
      - "nucliadb_client/VERSION"

jobs:
  build_wheels:
    name: Build wheels on ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install requirements
        run: pip install -r nucliadb_client/requirements.txt

      - name: Install nucliadb_client
        run: pip install -e ./nucliadb_client

      - name: Build wheels
        run: pip wheel --no-deps -w dist nucliadb_client

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
